/* Autogenerated by hxtools bin2c */
#ifdef __cplusplus
extern "C" {
#endif

/* Autogenerated from code.js */
static const unsigned char bin2c_code_js[717] = "(() => {\12    const ws = new WebSocket('ws://192.168.1.177:80/ws')\12    var txt = document.getElementById(\"debug\");\12    var button = document.getElementById(\"button\");\12    ws.onopen = () => {\12        console.log('ws opened on browser')\12        ws.send('hello world')\12    }\12    ws.onmessage = (message) => {\12        //console.log(`message received ` + message.data)\12        const s = message.data.split(\"=\");\12        //console.log(s);\12        if (s[0] == \"eko\") {            \12            txt.innerHTML += \"<br>\" + s[1];\12        }\12        if (s[0] == \"count\") {\12            ws.send(\"message=yyy\");\12        }\12    }\12    button.onclick = function() {\12        ws.send('message=aaa');\12    } \12    \12    console.log(\"ok\");\12})()\012";

#ifdef __cplusplus
} /* extern "C" */
#endif
