/* Autogenerated by hxtools bin2c */
#ifdef __cplusplus
extern "C" {
#endif

/* Autogenerated from code.js */
static const unsigned char bin2c_code_js[378] = "(() => {\12    const ws = new WebSocket('ws://192.168.1.177:80/ws')\12    var txt = document.getElementById(\"debug\");\12    ws.onopen = () => {\12        console.log('ws opened on browser')\12        ws.send('hello world')\12    }\12    ws.onmessage = (message) => {\12        //console.log(`message received ` + message.data)\12        txt.innerHTML = message.data;\12    console.log(\"ok\");\12})()\012";

#ifdef __cplusplus
} /* extern "C" */
#endif
