/* Autogenerated by hxtools bin2c */
#ifdef __cplusplus
extern "C" {
#endif

/* Autogenerated from page.html */
static const unsigned char bin2c_page_html[757] = "<!DOCTYPE html>\12<html>\12  <head>\12    <meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\" />\12<!-- \12    <meta http-equiv=\"refresh\" content=\"4\">\12--!>\12    <title>Debug</title>\12    <style>\12    .bb {\12        font-size: 80px;\12    }\12    </style>\12    <style>\12            html, body {\12                overflow: hidden;\12                width: 100%;\12                height: 100%;\12                margin: 0;\12                padding: 0;\12            }\12            #renderCanvas {\12                width: 100%;\12                height: 100%;\12                touch-action: none;\12            }\12     </style>\12  </head>\12  <body>\12  TAG\12  <button type=\"button\" id=\"button\">click</button> \12  <div id=\"debug\"> </div>\12  <script>\12JSCODE\12  </script>\12\12  </body>\12  </html>\012";

#ifdef __cplusplus
} /* extern "C" */
#endif
